function(enable_default_sanitizers target)
  if(NOT CMAKE_BUILD_TYPE MATCHES "Release")
    if(ENABLE_ASAN)
      target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
      target_link_libraries(${target} PRIVATE -fsanitize=address)
    endif()
    if(ENABLE_UBSAN)
      target_compile_options(${target} PRIVATE -fsanitize=undefined -fno-omit-frame-pointer)
      target_link_libraries(${target} PRIVATE -fsanitize=undefined)
    endif()
    if(ENABLE_TSAN)
      target_compile_options(${target} PRIVATE -fsanitize=thread -fno-omit-frame-pointer)
      target_link_libraries(${target} PRIVATE -fsanitize=thread)
    endif()
  endif()
endfunction()
