version: "3.9"
services:
  engine:
    build: ../engine
    image: mini-hft/engine:dev
    ports: ["8080:8080"]
  api:
    build: ../api
    image: mini-hft/api:dev
    environment:
      - ENGINE_URL=http://engine:8080
    ports: ["8000:8000"]
    depends_on: ["engine"]
  web:
    build: ../web
    image: mini-hft/web:dev
    environment:
      - NEXT_PUBLIC_API_BASE=http://api:8000
    ports: ["3000:3000"]
    depends_on: ["api"]
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: dev
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]
    depends_on: ["engine"]